/**
 * Generates low-quality image placeholders (LQIP) for the static artwork.
 *
 * `next/image` can work these out on its own, but only for images it can see at
 * build time through a static `import` — ours are referenced by path out of
 * /public, so it cannot. Without a placeholder every illustration on the page
 * pops in from nothing, which on a slow connection is a screen of empty boxes.
 *
 * Each image is drawn into a 16px-wide canvas and written out as a base64 WebP,
 * around 200 bytes each. They are inlined into the HTML, so a visitor sees a
 * blurred shape of the right colour immediately and no request is made for it.
 *
 * Re-run after adding or replacing artwork:  node scripts/generate-blur.mjs
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, posix } from 'node:path';

const PORT = process.env.CDP_PORT || '9333';
const DIRS = ['public/editorial', 'public/product', 'public/soon', 'public/backers', 'public/careers'];
const EXT = /\.(png|jpe?g|webp)$/i;

function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const name of entries) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (EXT.test(name)) out.push(full);
  }
  return out;
}

async function rpc(ws, id, method, params = {}) {
  return new Promise((res, rej) => {
    const on = (e) => {
      const m = JSON.parse(e.data);
      if (m.id === id) {
        ws.removeEventListener('message', on);
        if (m.error) rej(new Error(method + ': ' + JSON.stringify(m.error)));
        else res(m.result);
      }
    };
    ws.addEventListener('message', on);
    ws.send(JSON.stringify({ id, method, params }));
    setTimeout(() => rej(new Error('timeout ' + method)), 60000);
  });
}

function shrink(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const w = 16;
      const h = Math.max(1, Math.round((img.height / img.width) * w));
      const c = document.createElement('canvas');
      c.width = w;
      c.height = h;
      const ctx = c.getContext('2d');
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = 'high';
      ctx.drawImage(img, 0, 0, w, h);
      resolve(c.toDataURL('image/webp', 0.62));
    };
    img.onerror = () => resolve('');
    img.src = src;
  });
}

const targets = await (await fetch(`http://127.0.0.1:${PORT}/json/list`)).json();
const page = targets.find((t) => t.type === 'page');
if (!page) throw new Error('No Chrome page target. Start headless Chrome with --remote-debugging-port=' + PORT);
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((r) => ws.addEventListener('open', r, { once: true }));
let id = 0;
const call = (m, p) => rpc(ws, ++id, m, p);
await call('Runtime.enable');

const files = DIRS.flatMap(walk).sort();
const entries = [];
for (const file of files) {
  const mime = /\.png$/i.test(file) ? 'image/png' : /\.webp$/i.test(file) ? 'image/webp' : 'image/jpeg';
  const dataUrl = `data:${mime};base64,` + readFileSync(file).toString('base64');
  const res = await call('Runtime.evaluate', {
    expression: `(${shrink.toString()})(${JSON.stringify(dataUrl)})`,
    awaitPromise: true,
    returnByValue: true,
  });
  const blur = res.result.value;
  if (!blur) {
    console.warn('skipped (could not decode):', file);
    continue;
  }
  const publicPath = '/' + posix.join(...file.split(/[\\/]/).slice(1));
  entries.push([publicPath, blur]);
  console.log(publicPath.padEnd(44), blur.length + ' bytes');
}
ws.close();

const body = entries.map(([k, v]) => `  '${k}':\n    '${v}',`).join('\n');
writeFileSync(
  'lib/image-blur.ts',
  `/**
 * Generated by scripts/generate-blur.mjs — do not edit by hand.
 *
 * 16px-wide WebP previews of the static artwork, inlined so an illustration has
 * something to show before its real file arrives. Re-run the script after
 * adding or replacing anything under public/editorial, /product, /soon,
 * /backers or /careers.
 */
export const IMAGE_BLUR: Record<string, string> = {
${body}
};

/** Placeholder props for a public-path image, or nothing if it has no preview. */
export function blurProps(src: string) {
  const blurDataURL = IMAGE_BLUR[src];
  return blurDataURL ? ({ placeholder: 'blur', blurDataURL } as const) : {};
}
`,
);
console.log('\\nwrote lib/image-blur.ts with ' + entries.length + ' placeholders');
